name: monitor-perf
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38he774522_1000
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.0=py38h7a1dbc1_0
  - chardet=3.0.4=py38_1003
  - click=7.1.2=py_0
  - cryptography=2.9.2=py38h7a1dbc1_0
  - dash=1.13.4=pyh9f0ad1d_0
  - dash-bootstrap-components=0.10.3=pyh9f0ad1d_0
  - dash-core-components=1.10.1=pyh9f0ad1d_0
  - dash-html-components=1.0.3=pyh9f0ad1d_0
  - dash-renderer=1.5.1=pyh9f0ad1d_0
  - dash-table=4.8.1=pyh9f0ad1d_0
  - flask=1.1.2=py_0
  - flask-compress=1.5.0=py_0
  - future=0.18.2=py38_1
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=2.10=py_0
  - intel-openmp=2020.1=216
  - itsdangerous=1.1.0=py_0
  - jinja2=2.11.2=py_0
  - markupsafe=1.1.1=py38he774522_0
  - mkl=2020.1=216
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.1.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - numpy=1.18.5=py38h6530119_0
  - numpy-base=1.18.5=py38hc3f5095_0
  - openssl=1.1.1g=he774522_0
  - pandas=1.0.5=py38h47e9c7a_0
  - pip=20.1.1=py38_1
  - plotly=4.8.2=py_0
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py38_0
  - python=3.8.3=he1778fa_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py38he774522_1
  - requests=2.24.0=py_0
  - retrying=1.3.3=py_2
  - setuptools=49.2.0=py38_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h2a8f88b_0
  - urllib3=1.25.9=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py38_0
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_0
  - yaml=0.2.5=he774522_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
      - gunicorn==20.0.4
      - randomheaders==1.2
prefix: C:\Users\USER\Anaconda3\envs\monitor-perf

